# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c5054d087410b8c171a53098c13b37f76c54977530f6b2fedff779e6e9d4fbfd92e16a3e3608815525d1e63fe6096841310749ae1ecda06a7add7f03e952829c

test:
  secret_key_base: 89e950499e54e6177578916fd5a9778dcca78a616d830b2673ef035829f556978562897ef419b19c2259e15273225b20223132eaeeb09acdf0a182954ea129d6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
